-- phpMyAdmin SQL Dump
-- version 3.5.2.2
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Jan 03, 2013 at 05:03 AM
-- Server version: 5.5.27
-- PHP Version: 5.4.7

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `zoopedia`
--

-- --------------------------------------------------------

--
-- Table structure for table `animals`
--

CREATE TABLE IF NOT EXISTS `animals` (
  `Animal Id` int(100) NOT NULL,
  `Name` varchar(200) NOT NULL,
  `Type` varchar(200) NOT NULL,
  `Area` varchar(300) NOT NULL,
  `Habitat` varchar(300) NOT NULL,
  `Food` varchar(300) NOT NULL,
  `Size` varchar(300) NOT NULL,
  `Babies` varchar(300) NOT NULL,
  `Characteristic` varchar(500) NOT NULL,
  `Video_link` varchar(1000) NOT NULL,
  `Image1` varchar(500) NOT NULL,
  `Image2` varchar(500) NOT NULL,
  PRIMARY KEY (`Animal Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `animals`
--

INSERT INTO `animals` (`Animal Id`, `Name`, `Type`, `Area`, `Habitat`, `Food`, `Size`, `Babies`, `Characteristic`, `Video_link`, `Image1`, `Image2`) VALUES
(1, 'Cheetah', 'Mammals', 'Southern and eastern Africa', 'Savanna ', 'Antelope ', 'About 4 feet long, with a 2-1/2-foot long tail ', 'Cheetah cubs have a silvery mane on their neck and shoulders that disappears as they get older. ', 'Cheetahs cannot roar, but they do growl, hiss, purr and chirp', 'http://www.youtube.com/embed/DRxsP2YMaOI', 'images/slide/cheetah-1.jpg', 'images/slide/cheetah-2.jpg'),
(2, 'Lion', 'Mammals', 'Africa, south of the Sahara Desert', 'Savannah with thick brush  ', 'Antelope, zebra, and other hoofed animals  ', 'Males are 5 to 8 feet long, females are 4 1/2 to 5 1/2 feet long ', 'Cubs can nurse from any female in the pride, not just their own mother. ', 'When one lion yawns or roars, the rest of the pride often does the same', 'http://www.youtube.com/embed/T2gq5fwbk-Q', 'images/slide/lion-1.jpg', 'images/slide/lion-2.jpg'),
(3, 'Gorilla', 'Mammals', 'Central Africa', 'Lowland tropical rain forests', 'Fruits, seeds, leaves, and insects', '5 to 6 feet tall', 'A baby gorilla stays close to its mother and sleeps in her nest until it is 4 to 6 years old', 'No two gorilla noses are alike. Scientists use close-up photographs of gorilla faces to tell who is who', 'http://www.youtube.com/embed/T2gq5fwbk-Q', 'images/slide/gorilla-1.jpg', 'images/slide/gorilla-2.jpg'),
(4, 'Panda', 'Mammals', 'China', ' Forests', 'Bamboo, grasses, bulbs, some insects and fruit', '5 feet long', 'Cubs are born hairless and with their eyes closed', 'They seem pretty quiet, but giant pandas can bleat, roar, growl, and honk', 'http://www.youtube.com/embed/bGizjaMieyE&NR=1', 'images/slide/panda-1.jpg', 'images/slide/panda-2.jpg'),
(5, 'Zebra', 'Mammals', 'Eastern and southern Africa', 'Grasslands and semi-deserts', 'Grass and leaves', '4 to 5 feet tall at the shoulder', 'Foals can walk just 20 minutes after they are born', 'Underneath its hair, a zebra''s skin is black', 'http://www.youtube.com/embed/AGl4VdHVG_8', 'images/slide/zebra-1.jpg', 'images/slide/zebra-2.jpg'),
(6, 'Rhinoceros', 'Mammals', 'Africa and some areas of Asia', 'Grasslands and savannahs', 'Grasses, leaves, and the shoots of bushes and trees', '4,000-6,000 pounds', 'Rhino calves are born without horns', 'Rhinos have poor eyesight but excellent sense of smell and hearing', 'http://www.youtube.com/embed/I_2JTuz5V4E', 'images/slide/rhino-1.jpg', 'images/slide/rhino-2.jpg'),
(7, 'Giraffe', 'Mammals', 'Mostly Africa', 'Savannah', 'Acacia Leaves', '16-18 feet', 'The infants can stand in half an hour and run with their mothers an incredible ten hours after birth.', 'Giraffes are the world''s tallest mammals, thanks to their towering legs and long necks', 'http://www.youtube.com/embed/DXeu_2cFVUM', 'images/slide/giraffe-1.jpg', 'images/slide/giraffe-2.jpg'),
(8, 'Gazelle', 'Mammals', 'Africa and Asia', 'Open grass plains', 'Herbs, foliage from shrubs, short grasses and shoots', '30 to 36 inches', 'The fawn eats its first solid food at about 1 month, but is nursed for 6 months. The only relatively long-lasting relationship in gazelle society is that of a mother and her most recent offspring.', 'In addition to running at high speeds, Thomson''s gazelles also use a bounding leap, called "stotting" or "pronking," to avoid predators', 'http://www.youtube.com/embed/CkMprdgnXWI', 'images/slide/gazelle-1.jpg', 'images/slide/gazelle-2.jpg'),
(9, 'Bongo', 'Mammals', 'Eastern, Western and Central Africa', 'Dense forests and bamboo thickets', 'Leaves, Bark, Grasses', '1.7m - 2.5m (5.5ft - 8.25ft)', 'Bongo calves grow relatively fast and their horns begin to show by the time they are three or four months old.', 'To help them to cool down in the heat, Bongos wallow in mud which they then rub onto a tree as a way of polishing their smooth and heavy horns', 'http://www.youtube.com/embed/z7f7wgdRLbk', 'images/slide/bongo-1.jpg', 'images/slide/bongo-2.jpg'),
(10, 'Elephant', 'Mammals', 'Asia and Africa', 'Rainforest and flood plains', 'Grass, Fruit, Roots', '2m - 3.6m (7ft - 12ft)', 'The infant elephant remains with its mother until it is around 5 years old and gains its independence, with males often leaving the herd and female calves staying.', 'One old elephant related myth is that elephants are afraid of mice', 'http://www.youtube.com/embed/k1rgN19p5P8', 'images/slide/elephant-1.jpg', 'images/slide/elephant-2.jpg'),
(11, 'Kangaroo', 'Mammals', 'Australia and the Indonesian island of New Guinea', 'Dry forests, desert and grassland', 'Grass, Seeds, Flowers', '0.6-1.5m (1.9-4.9ft)', 'Kangaroos have a deep pouch on their front in which to carry their young. A baby kangaroo is called a joey.', 'Kangaroos are most well known for their ability to jump a phenomenal distance', 'http://www.youtube.com/embed/9YGC2TtpVEs', 'images/slide/kangaroo-1.jpg', 'images/slide/kangaroo-2.jpg'),
(12, 'Wallaby', 'Mammals', 'Australian continent and its surrounding islands', 'Forest and shrubland', 'Grasses, Fruits, Seeds, Leaves', '30-180cm (12-71in)', 'The female wallaby has a pouch on her tummy in which to raise her young. The female wallaby gives birth to a single baby wallaby (occasionally twins), known as a joey.', 'The tail of the wallaby is often as long as the wallaby''s body and plays a critical role as a balance aid and is often used in self-defense', 'http://www.youtube.com/embed/DLcuZ-HnHZc', 'images/slide/wallaby-1.jpg', 'images/slide/wallaby-2.jpg'),
(13, 'Koala', 'Mammals', 'South-eastern Australia', 'Eucalyptus, inland and coastal forests', 'Eucalyptus leaves', '60cm - 85cm (24in - 34in)', 'The young Koala then clings onto it''s mother''s back where it tends to remain for another few months or until the next season''s young has developed and is ready to leave the pouch.', 'Having two opposable thumbs and three fingers on each hand means that Koalas are able to grip onto even the smoothest of bark when climbing and feeding in the trees', 'http://www.youtube.com/embed/SmKKLy3T0UI', 'images/slide/koala-1.jpg', 'images/slide/koala-2.jpg'),
(14, 'Annas Hummingbird', 'Birds', 'West Coast of North America, from southern Canada to northern Baja California, Mexico', 'Chaparral near open woodland, urban and suburban areas', 'Flower nectar, small insects, and tree sap', 'About 4 inches long', 'Usually 2 eggs are laid; chicks hatch after about 23 days', 'A hummingbird''s heart beats 1,260 times a minute', 'http://www.youtube.com/embed/zdmTBjhZmyc', 'images/slide/hummingbird-1.jpg', 'images/slide/hummingbird-2.jpg'),
(15, 'Eagle', 'Birds', 'Canada, United States, and northwest Mexico', 'Coastlines, lakes, rivers, swamps, and marshes', 'Fish, rabbits, squirrels, other birds, and even young deer', '29 to 42 inches long', '1 to 3 eggs are laid; eaglets hatch 35 days later', 'The bald eagle isn''t really bald! Its head is covered with short, white feathers. The term "bald" may be from the Old English word "balde" that meant white', 'http://www.youtube.com/embed/hecXupPpE9o', 'images/slide/eagle-1.jpg', 'images/slide/eagle-2.jpg'),
(16, 'Bee Eater', 'Birds', 'Africa, Asia, southern Europe, Australia, and New Guinea', 'Burrows tunnelled into the side of sandy banks', 'Insects, especially bees and wasps', '6 to 14 inches long (depending on species)', 'Eggs are laid in clutches of 2 to 9 and hatch after about 20 days', 'Before eating its meal, a bee eater removes the sting by hitting and rubbing the insect on a hard surface to extract most of the venom', 'http://www.youtube.com/embed/Y3mF4yb3pOE', 'images/slide/bee eater-1.jpg', 'images/slide/bee eater-2.jpg'),
(17, 'Emu', 'Birds', 'Australia', 'Grassy plains and open forests', 'Seeds, leaves, insects, small reptiles, and fruit', '5 to 6 feet tall', 'Brown-and-cream striped chicks are able to feed themselves but stay with their father for about 18 months', 'Emu eggs are dark green and are the same size and color as an avocado', 'http://www.youtube.com/embed/2RVZvUJDTUE', 'images/slide/emu-1.jpg', 'images/slide/emu-2.jpg'),
(18, 'Flamingo', 'Birds', 'South America and the Caribbean; small population in the Galápagos Islands', 'Large shallow lakes and lagoons', 'Brine flies, shrimp, and mollusks', '31 to 57 inches tall, weighs up to 6 pounds', 'Usually 1 egg is laid, from which a chick hatches after about 30 days', 'The Caribbean flamingo is the "brightest" of all flamingos, showing its true colors of red, pink, or orange on its legs, bill, and face', 'http://www.youtube.com/embed/887wtl3YHA0', 'images/slide/flamingo-1.jpg', 'images/slide/flamingo-2.jpg'),
(19, 'Hawk', 'Birds', 'North and Central America', 'Open and wooded areas', 'Rodents, rabbits, and birds', 'Body is 18 to 22 inches long; wingspan is 47 to 56 inches', 'Chicks are called eyasses (EYE-ess-ez', '', 'http://www.youtube.com/embed/hjmJla-q880', 'images/slide/hawk-1.jpg', 'images/slide/hawk-2.jpg'),
(20, 'Finch', 'Birds', 'Northern Hemisphere, Neotropics, Hawaiian Islands', 'Open meadow areas', 'Seed eating songbirds', 'Body is 3 to 10 inches long', 'A baby finch is called a chick', '', 'http://www.youtube.com/embed/0e1V0rVFHdQ', 'images/slide/finch-1.jpg', 'images/slide/finch-2.jpg'),
(21, 'Blue Poison Frog ', 'Amphibians', 'Central and South America', 'Rain forest', 'Ants, termites, centipedes, beetles', '1 inch', 'Tadpoles', 'A group of poison frogs is called an "army"', 'http://www.youtube.com/embed/qdsJQWR9oDk', 'images/slide/bpf-1.jpg', 'images/slide/bpf-2.jpg'),
(22, 'Caecilian', 'Amphibians', 'Central Africa, Southeast Asia, southern Mexico to Argentina', 'Loose soil and ground liter in tropical forests, or in rivers or streams', 'Worms, termites, beetle pupae, snails, small snakes, frogs, lizards', 'From 3 1/2 inches to about 5 feet long, depending on the species', 'In some species, larvae hatch from eggs then grow and change into adult form. Other types of caecilians give birth to live young that develop inside the mother before being born', 'Caecilians have toxic glands in their skin that sometimes protect them from being eaten by other animals', 'http://www.youtube.com/embed/DMvL4zOLSeM', 'images/slide/caecilian-1.jpg', 'images/slide/caecilian-2.jpg'),
(23, 'Fire Salamander', 'Amphibians', 'Europe, Africa, and Asia', 'Forests', 'Insects, earthworms, small frogs, spiders, and slugs', 'Up to 8 inches long (about as long as a table knife)', 'Fully formed larvae or fully formed salamander, depending on subspecies', 'The fire salamander is the only amphibian that does not hatch from an egg. Instead, the babies develop inside the mother''s body', 'http://www.youtube.com/embed/3o-S0GWyYEI', 'images/slide/salamander-1.jpg', 'images/slide/salamander-2.jpg'),
(24, 'Waxy Tree Frog', 'Amphibians', 'Central and South America', 'Trees and vegetation near freshwater ponds and lagoons in savannas, shrubland, and forested areas', 'Insects', '3 inches', 'Tadpoles', 'Waxy tree frogs make a leaf nest in which they lay their eggs. The nest hangs over water and when the eggs hatch, the tadpoles drop into the water where they develop into frogs', 'http://www.youtube.com/embed/Ce8a5bFQexA', 'images/slide/wtf-1.jpg', 'images/slide/wtf-2.jpg'),
(25, 'Yellow Legged Frog', 'Amphibians', 'Southern California', 'Southern Sierra Nevada Mountains: lakes, ponds, meadow streams, isolated pools, sunny riverbanks; in mountains of Southern California, rocky streams in narrow canyons and in the chaparral belt', 'Beetles, ants, bees, wasps, flies, and dragonflies', '1 1/2 to 3 1/2 inches long', 'Tadpoles hatched from eggs laid in shallow water', 'Water is absorbed through the mountain yellow-legged frog''s skin. It never has to drink water', 'http://www.youtube.com/embed/HMgqE8_CJac', 'images/slide/ylf-1.jpg', 'images/slide/ylf-2.jpg'),
(26, 'Alligator', 'Reptiles', 'Southeastern United States', 'Swamps, marshes, lakes, and slow-moving rivers', 'Fish, turtles, mammals, and birds', 'Up to 15 feet long', 'When they hatch from their eggs, alligators are 10 inches long and black with yellow stripes and splotches', 'The name "alligator" comes from the Spanish el legarto, meaning "the lizard."', 'http://www.youtube.com/embed/lGU139zbIt8', 'images/slide/alligator-1.jpg', 'images/slide/alligator-2.jpg'),
(27, 'Anaconda', 'Reptiles', 'South America', 'Rain forests and wetlands', 'Wild pigs, deer, birds, turtles, capybaras, caimans, and jaguars', 'Up to 30 feet (almost as long as a school bus!)', 'Measure 2 feet long at birth and take care of themselves from the start', 'A group of anacondas is called a "bed" or "knot."', 'http://www.youtube.com/embed/CBpFS_Puutk', 'images/slide/anaconda-1.jpg', 'images/slide/anaconda-2.jpg'),
(28, 'Python', 'Reptiles', 'Africa, Madagascar, Southeast Asia, and Australia', 'Rain forest, grassland and savanna, woodland, and swamps', 'Rodents, birds, lizards, monkeys, pigs, or antelope, depending on the size of the snake', '23 inches to 33 feet, depending on the species', 'Hatch from eggs and take care of themselves from the start', 'Pythons have fangs, but do not produce venom', 'http://www.youtube.com/embed/3ZYyx3HC1sk', 'images/slide/python-1.jpg', 'images/slide/python-2.jpg'),
(29, 'Sungazer', 'Reptiles', 'South Africa', 'Grassland and desert', 'Mostly insects, sometimes mice', 'Up to 15 1/2 inches', 'Young are born live, measuring 4 to 6 inches long', 'During the winter, sungazer lizards hibernate in their burrows', 'http://www.youtube.com/embed/pqAVftrruhU', 'images/slide/sungazer-1.jpg', 'images/slide/sungazer-2.jpg'),
(30, 'Tortoise', 'Reptiles', 'Everywhere on earth like Galápagos Islands, off the coast of Ecuador', 'Flat, grassy areas and rocky, volcanic outcroppings', 'Cactus, fruit, flowers, leaves, and grasses', 'Up to 6 feet long and 4 to 5 feet across', 'A hatchling weighs about 3 ounces at birth, but can grow to 500 pounds', 'These tortoises can live a long time. Some of those at the San Diego Zoo are more than 100 years old!', 'http://www.youtube.com/embed/uNvtJ0jViOw', 'images/slide/tortoise-1.jpg', 'images/slide/tortoise-2.jpg'),
(31, 'Guitarfish', 'Fish', 'Indo-West Pacific: Red Sea and East Africa to Papua New Guinea, north to Japan, south to New South Wales, Australia', 'Shallow water fairly close to shore', 'Crustaceans and mollusks', '2.44 m (8 feet)', 'The newborn pups are about 45 cm (18 in) in length. They disperse immediately after birth to live independent lives without parental care', 'In protected environments guitarfish live for about seven years', 'http://www.youtube.com/embed/HuQ6p3v0DKc', 'images/slide/guitarfish-1.jpg', 'images/slide/guitarfish-2.jpg'),
(32, 'Goatfish', 'Fish', 'Western Atlantic Ocean from Brazil to north-eastern United States (New Jersey)', 'Reefs, shallow water', 'Carnivore. Shrimp, crabs, bottom-dwelling invertebrates, clams, and clam worms', '30 cm (1 ft)', 'The newborn pups are about 45 cm (18 in) in length. They disperse immediately after birth to live independent lives without parental care', 'All goatfish have the ability to change their coloration depending on their current activity', 'http://www.youtube.com/embed/K9_ZHICoiho', 'images/slide/goatfish-1.jpg', 'images/slide/gaotfish-2.jpg'),
(33, 'Moonfish', 'Fish', 'The geographic range of this fish covers most of tropical and temperate waters of the world’s greatest oceans', 'Tropical', 'Squid and krill', '2 metres (6.6 ft)', 'During the early years of their lives, the slender hatchlings transform and grow at a very fast rate', 'These fish migrate over long distances depending on the oceanic environmental conditions', 'http://www.youtube.com/embed/K9_ZHICoiho', 'images/slide/moonfish-1.jpg', 'images/slide/moonfish-2.jpg'),
(34, 'Moray eels', 'Fish', 'Tropical and sub-tropical regions', 'Coastal and deep waters', 'Fish, Squid, Crustaceans', '11-400cm (4-157in)', 'It can take up to year for the moray eel larvae to have grown big enough to swim down to the ocean floor to join the community below', 'They tend to do their hunting at night and rely on smell to help them get their prey', 'http://www.youtube.com/embed/tGUvKpw79r4', 'images/slide/moray eel-1.jpg', 'images/slide/moray eel-2.jpg'),
(35, 'Shark', 'Fish', 'Western Cape, South Africa, South Australia, West coast USA, Guadalupe Island Mexico and New Zealand', 'Near the coast and in deep oceanic waters', 'Fish, other sharks, seals, dolphins', '6.1 metres', 'Reproduce slowly with litters of 2 - 10 baby sharks, called pups. Each pup is between 1.2 - 1.7 meters long when it is born', 'One of the most successful predators in the world', 'http://www.youtube.com/embed/O2FInaOCqoo', 'images/slide/shark-1.jpg', 'images/slide/shark-2.jpg'),
(36, 'Stingray', 'Fish', 'Warmer waters around the globe', 'Warm, tropical waters', 'Crustaceans, Snails, Fish', '50cm - 200cm (19.6in - 79in)', 'Stingrays breed during the winter and the female stingray gives birth to live young usually between 5 and 15 baby stingrays, known as a litter', 'The stingray uses the stinger on the end of it''s long tail pierce through and stop it''s prey before it can escape', 'http://www.youtube.com/embed/Nbuu1Fa-c1k', 'images/slide/stingray-1.jpg', 'images/slide/stingray-2.jpg'),
(37, 'Tarpon', 'Fish', 'Range from Virginia to central Brazil in the western Atlantic, along the coast of Africa in the eastern Atlantic, and all through the Gulf of Mexico and Caribbean Sea', 'Shallow coastal waters and estuaries', 'Mullets, pinfish, marine catfishes, Atlantic needlefish, sardines, shrimp, and crabs', '8 feet', 'A female tarpon can lay upto 12 million eggs at once', 'Externally, the almost vertical, silvery sides made up of large scales are the most distinctive feature of the tarpon', 'http://www.youtube.com/embed/mDz1d1E8ro4', 'images/slide/tarpon-1.jpg', 'images/slide/tarpon-2.jpg'),
(38, 'Tripletail', 'Fish', 'Atlantic Ocean and Tropical seas', 'Tropical and subtropical seas', 'Crabs and shrimps', '3.5 feet', 'A young tripletail looks like a floating mangrove leaf', 'The name "tripletail" is given because of the fish''s three rounded fins: dorsal, caudal, and anal', 'http://www.youtube.com/embed/xhvFfl15HNU', 'images/slide/tripletail-1.jpg', 'images/slide/tripletail-2.jpg'),
(39, 'Toadfish', 'Fish', 'Caribbean sea', 'Sandy, rocky, and muddy bottoms on oyster reefs, shoal water, among eelgrass, hollows, or dens', 'American oysters, worms, shrimp, amphipods, crabs, hermit crabs, mollusks, squid, and small fish', '12 inches', 'When the eggs hatch the young toadfish stay attached to the yolk for some time. Even when the young have started to swim the adult still protects its young', 'They are capable of changing colour to match the bottom, and their eyes are blue', 'http://www.youtube.com/embed/sFE-LBD9MyM', 'images/slide/toadfish-1.jpg', 'images/slide/toadfish-2.jpg');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
