var amphi_json = 
	{
 "resizeType": "auto",
 "disableOnMobile": true,
 "pauseTime": "3000",
 "align": "left",
 "auto": true,
 "hideOnMouseOut": true,
 "vertical": false,
 "ease": "easeOut",
 "continuous": true,
 "loop": true,
 "sliderEffect": "slide",
 "speed": "500",
 "fadeDuration": "500",
 "pause": "1000",
 "stopAtInteraction": false,
 "resumeDuration": "3000",
 "innernavbaritem.spacing": "0px",
 "innernumbers.spacing": "0px",
 "enableQuickSlideChange": false,
 "tooltip.show": true,
 "tooltip.offsX": "10px",
 "tooltip.offsY": "-40px",
 "tooltip.width": "200px",
 "tooltip.height": "70px",
 "tooltip.speed": "500",
 "tooltip.easing": "easeOut",
 "tooltip.side": "right",
 "tooltip.reverseSide": false,
 "innerbutton.back.opacity": 1,
 "innerbutton.back.hideOnMouseOut": true,
 "innerbutton.back.mouseOutEffect": "fadeIn",
 "innerbutton.back.mouseOutEffectDuration": "200",
 "innerbutton.back.mouseOutEffectEasing": "linear",
 "innerbutton.back.halign": "center",
 "innerbutton.back.valign": "middle",
 "innerbutton.back.left": "-342px",
 "innerbutton.back.top": "0px",
 "innerbutton.next.opacity": 1,
 "innerbutton.next.hideOnMouseOut": true,
 "innerbutton.next.mouseOutEffect": "fadeIn",
 "innerbutton.next.mouseOutEffectDuration": "200",
 "innerbutton.next.mouseOutEffectEasing": "linear",
 "innerbutton.next.halign": "right",
 "innerbutton.next.valign": "middle",
 "innerbutton.next.left": "25px",
 "innerbutton.next.top": "0px",
 "innerplaypause.opacity": 1,
 "innerplaypause.hideOnMouseOut": false,
 "innerplaypause.mouseOutEffect": "fadeIn",
 "innerplaypause.mouseOutEffectDuration": "1000",
 "innerplaypause.mouseOutEffectEasing": "linear",
 "innerplaypause.halign": "center",
 "innerplaypause.valign": "middle",
 "innerplaypause.left": "-328px",
 "innerplaypause.top": "130px",
 "innernavbar.hideOnMouseOut": false,
 "innernavbar.mouseOutEffect": "fadeIn",
 "innernavbar.mouseOutEffectDuration": "1000",
 "innernavbar.mouseOutEffectEasing": "linear",
 "innernavbar.halign": "left",
 "innernavbar.valign": "top",
 "innernavbar.left": "0px",
 "innernavbar.top": "0px",
 "innernavbaritem.orientation": "horizontal",
 "innernavbar.orientation": "horizontal",
 "innernavbar.scrollerOrientation": "horizontal",
 "innernavbar.scrollerType": "noScroll",
 "innernavbar.opacity": "1",
 "innernavbaritem.contentType": "image & text to right",
 "innerbullets.valign": "top",
 "innerbullets.halign": "right",
 "innerbullets.left": "0px",
 "innerbullets.hideOnMouseOut": false,
 "innerbullets.mouseOutEffect": "slideFromBottom",
 "innerbullets.mouseOutEffectEasing": "linear",
 "innerbullets.mouseOutEffectDuration": "500",
 "innerbulletsitem.orientation": "vertical",
 "innerbullets.orientation": "vertical",
 "innerbullets.opacity": "0.6",
 "innerbullets.scrollerType": "noScroll",
 "innernumbers.valign": "middle",
 "innernumbers.halign": "left",
 "innernumbers.left": "40px",
 "innernumbers.hideOnMouseOut": false,
 "innernumbers.mouseOutEffect": "fadeIn",
 "innernumbers.mouseOutEffectEasing": "linear",
 "innernumbers.mouseOutEffectDuration": "1000",
 "innernumbersitem.orientation": "horizontal",
 "innernumbers.orientation": "horizontal",
 "innernumbers.scrollerOrientation": "horizontal",
 "innernumbers.scrollerType": "noScroll",
 "innernumbers.opacity": "1",
 "innerthumbscroll.opacity": "1",
 "innerthumbscroll.scrollerOrientation": "horizontal",
 "innerthumbscroll.scrollerType": "noScroll",
 "thumbscroll.scrollerOrientation": "horizontal",
 "innerthumbscrollitem.orientation": "horizontal",
 "thumbscrollitem.orientation": "horizontal",
 "innerthumbscrollitemthumb.hover.mouseOverEffect": false,
 "innerthumbscrollitemthumb.hover.mouseOverEffectEasing": "linear",
 "innerthumbscrollitemthumb.hover.mouseOverEffectDuration": "2000",
 "innernavbaritemthumb.hover.mouseOverEffect": false,
 "innernavbaritemthumb.hover.mouseOverEffectEasing": "linear",
 "innernavbaritemthumb.hover.mouseOverEffectDuration": "2000",
 "innerthumbscrollitemthumb.opacity": "1",
 "innerthumbscrollitemthumb.hover.opacity": "1",
 "innerthumbscrollitemthumb.active.opacity": "1",
 "innercurrentslide.halign": "left",
 "innercurrentslide.valign": "top",
 "innercurrentslide.left": "0px",
 "innercurrentslide.top": "0px",
 "innerthumbscroll.halign": "left",
 "innerthumbscroll.valign": "bottom",
 "innerthumbscroll.left": "5px",
 "innerthumbscroll.top": "-1px",
 "innernavbaritemthumb.opacity": "1",
 "innernavbaritemthumb.hover.opacity": "1",
 "innernavbaritemthumb.active.opacity": "1",
 "currentslide.opacity": "1",
 "innercurrentslide.opacity": "1",
 "thumbscroll_next.opacity": "1",
 "thumbscroll_back.opacity": "1",
 "innerthumbscroll_next.opacity": "1",
 "innerthumbscroll_back.opacity": "1",
 "caption.opacity": "1",
 "innercaption.opacity": "0.65",
 "subcaption.opacity": "1",
 "innersubcaption.opacity": "1",
 "navbar_back.opacity": "1",
 "navbar_next.opacity": "1",
 "innernavbar_back.opacity": "1",
 "innernavbar_next.opacity": "1",
 "innernumbers_back.opacity": "1",
 "innernumbers_next.opacity": "1",
 "innernumbers_back.halign": "left",
 "innernumbers_back.valign": "top",
 "innernumbers_back.left": "0px",
 "innernumbers_back.top": "0px",
 "innernumbers_next.halign": "left",
 "innernumbers_next.valign": "top",
 "innernumbers_next.left": "0px",
 "innernumbers_next.top": "0px",
 "innerbullets_back.opacity": "1",
 "innerbullets_next.opacity": "1",
 "innercurrentslide.hideOnMouseOut": false,
 "innercurrentslide.slideEffectEasing": "linear",
 "innercurrentslide.mouseOutEffectEasing": "linear",
 "innercurrentslide.mouseOutEffectDuration": "1000",
 "innercurrentslide.mouseOutEffect": "fadeIn",
 "innercurrentslide.slideEffect": "fadeIn",
 "innercaption.hideOnMouseOut": true,
 "innercaption.slideEffectEasing": "easeOut",
 "innercaption.mouseOutEffectEasing": "easeOut",
 "innercaption.mouseOutEffectDuration": "1000",
 "innercaption.mouseOutEffectDelay": "0",
 "innercaption.mouseOutEffect": "slideFromLeft",
 "innercaption.slideEffect": "slideFromLeft",
 "innersubcaption.hideOnMouseOut": true,
 "innersubcaption.slideEffectEasing": "easeOut",
 "innersubcaption.mouseOutEffectEasing": "easeOut",
 "innersubcaption.mouseOutEffectDuration": "1000",
 "innersubcaption.mouseOutEffect": "slideFromLeft",
 "innersubcaption.mouseOutEffectDelay": "0",
 "innersubcaption.slideEffect": "slideFromLeft",
 "relPath": "",
 "innerslider.left": "0px",
 "innerbullets.top": "0px",
 "imagearea.left": "0px",
 "innercaption_next.halign": "center",
 "innersubcaption_back.left": "0px",
 "innerthumbscroll.width": "594px",
 "innerthumbscroll.height": "57px",
 "innercaption.top": "0px",
 "innercaption_back.top": "0px",
 "imagearea.top": "0px",
 "backgroundType": "normal",
 "innerthumbscroll.mouseOutEffectDuration": "400",
 "innercaption.height": "230px",
 "innersubcaption.height": "200px",
 "innerbulletsitem.backgroundType": "normal",
 "innerthumbscrollitem.width": "88px",
 "innersubcaption_back.top": "0px",
 "innersubcaption_next.left": "0px",
 "innersubcaption.valign": "top",
 "innerthumbscroll.mouseOutEffectEasing": "swing",
 "innercaption_back.left": "0px",
 "innerimagearea.left": "0px",
 "innersubcaption.top": "60px",
 "innerthumbscroll.itemWidth": "95px",
 "innerthumbscroll.itemHeight": "65px",
 "innercaption.width": "125px",
 "innersubcaption_next.top": "0px",
 "tooltip.backgroundType": "normal",
 "innerthumbscrollitem.hover.backgroundType": "normal",
 "innerbullets.scrollerOrientation": "vertical",
 "innercaption.valign": "top",
 "innerimagearea.top": "0px",
 "innersubcaption_back.halign": "center",
 "innersubcaption_next.halign": "center",
 "effect": "boxRain",
 "innerbulletsitem.spacing": "10px",
 "innersubcaption_next.valign": "middle",
 "height": "250px",
 "innerthumbscroll.mouseOutEffect": "fadeIn",
 "gifPath": "includes/jQuerySlideshow/x.gif",
 "innerthumbscrollitem.spacing": "0px",
 "width": "250px",
 "innersubcaption.useSlideEffect": false,
 "innercaption_next.left": "0px",
 "innercaption.halign": "left",
 "innercaption_next.top": "0px",
 "innerbulletsitem.hover.backgroundType": "normal",
 "innercaption_next.valign": "middle",
 "innerbullets.height": "290px",
 "preloading": "includes/jQuerySlideshow/preloading.gif",
 "innercaption_back.halign": "center",
 "innercaption_back.valign": "middle",
 "innerthumbscroll.hideOnMouseOut": false,
 "innersubcaption.width": "54px",
 "innersubcaption.left": "0px",
 "innercaption.useSlideEffect": false,
 "innerbullets.backgroundType": "normal",
 "innercaption.left": "0px",
 "innerthumbscroll.orientation": "horizontal",
 "innerbulletsitem.active.backgroundType": "normal",
 "innersubcaption.halign": "left",
 "innerslider.top": "0px",
 "innerthumbscrollitem.active.backgroundType": "normal",
 "innerthumbscrollitem.backgroundType": "normal",
 "innerthumbscroll.backgroundType": "normal",
 "innerbullets.width": "10px",
 "innersubcaption_back.valign": "middle",
 "innerthumbscrollitem.height": "65px"
};


var amphi_source = [{"description":"","title":"Yellow Legged Frog","src":"includes/jQuerySlideshow/images/amphi/yellow_legged_frog3.jpg","target":"_self","link":""},{"description":"","title":"Yellow Legged Frog","src":"includes/jQuerySlideshow/images/amphi/yellow_legged_frog1.jpg","target":"_self","link":""},{"description":"","title":"Waxy Tree Frog ","src":"includes/jQuerySlideshow/images/amphi/waxy_tree4.jpg","target":"_self","link":""},{"description":"","title":"Fire Salamander","src":"includes/jQuerySlideshow/images/amphi/fire_salamander4.jpg","target":"_self","link":""},{"description":"","title":"Fire Salamander","src":"includes/jQuerySlideshow/images/amphi/fire_salamander3.jpg","target":"_self","link":""},{"description":"","title":"Caecilian","src":"includes/jQuerySlideshow/images/amphi/caecilian_1.jpg","target":"_self","link":""},{"description":"","title":"Blue Dart Frog","src":"includes/jQuerySlideshow/images/amphi/blue_dart_poison_frog3.jpg","target":"_self","link":""},{"description":"","title":"Blue Dart Poison Fron","src":"includes/jQuerySlideshow/images/amphi/blue_dart_poison_frog1.jpg","target":"_self","link":""}];
var amphi_tooltipsource = [{"src":"includes/jQuerySlideshow/images/amphi/yellow_legged_frog3tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/amphi/yellow_legged_frog1tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/amphi/waxy_tree4tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/amphi/fire_salamander4tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/amphi/fire_salamander3tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/amphi/caecilian_1tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/amphi/blue_dart_poison_frog3tooltip.jpg"},{"src":"includes/jQuerySlideshow/images/amphi/blue_dart_poison_frog1tooltip.jpg"}];
var amphi_slideshow = null;	

xtd_jQuerySlideshow(document).ready(function(){
	var $ = xtd_jQuerySlideshow;
	var jQuery = xtd_jQuerySlideshow;
	
	$("#amphiContainer").hide();
	
	// fix bug on webkit//
	if (jQuery.browser.webkit && document.readyState != "complete") {
		setTimeout( createJQuerySlideShow, 100 );
	} else {
		createJQuerySlideShow()
	}
		
	function createJQuerySlideShow() {

		if (document.readyState && document.readyState != "complete") {
			setTimeout( createJQuerySlideShow, 100 );
			return;
		}

		//show element first as height/width of auto elements is 0 if container is hidden//
		$("#amphiContainer").show();
		
		// create the slider
		amphi_slideshow = $("#amphi").jQuerySlideShow();
	}
});